from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_cors import CORS ### THIS STANDS FOR "CROSS ORGINS REQUEST"
### ALLOWS US TO SEND A REQUESTS THE THE BACKEND FROM A DIFFERENT URL
### THIS REMOVES THE CORS ERROR

"""start with the config file"""


app = Flask(__name__) # THIS ACTIVATES THE FLASK APPLICATIONS
CORS(app) # DISABLE THE CORS ERROR

app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///Juliuspractice.db" # 3 SLASHES
#SPECIFYING THE LOCATION OF THE LOCAL SQL WE'LL STORE ON OUR MACHINE


app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False
 # THIS MEANS WE WON'T TRACK ALL THE MODIFACTIONS MADE ONTO THE DATABASE

db = SQLAlchemy(app) # db == DATABASE # THIS CREATES A DATABASE INSTANCE


